name: Generate Threads RSS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python3 -m pip install -r requirements.txt

    - name: Run threads2rss
      run: |
        python3 threads2rss.py

    - name: Push RSS to repo
      run: |
        git config user.name "rss-bot"
        git config user.email "rss-bot@example.com"
        git add *.xml
        git commit -m "Update RSS feeds" || echo "No changes to commit"
        git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/mynewbie7/threads-rss-feed.git main
